ARG BASE_IMAGE=8-jdk-slim
FROM openjdk:$BASE_IMAGE

ARG ARTHAS_VERSION="3.3.9"
ARG MIRROR=false
ARG TIMEZONE=""
ENV TZ=Asia/Shanghai

ENV MAVEN_HOST=https://repo1.maven.org/maven2 \
    MIRROR_MAVEN_HOST=https://maven.aliyun.com/repository/public
RUN  apt-get update -y && \
     apt-get upgrade -y && \
     apt-get dist-upgrade -y && \
     apt-get -y autoremove && \
     apt-get clean && \
     apt-get install unzip wget -y

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# if use mirror change to aliyun mirror site
RUN if $MIRROR; then MAVEN_HOST=${MIRROR_MAVEN_HOST} ; fi && \
    wget -qO /tmp/arthas.zip "${MAVEN_HOST}/com/taobao/arthas/arthas-packaging/${ARTHAS_VERSION}/arthas-packaging-${ARTHAS_VERSION}-bin.zip" && \
    mkdir -p /opt/arthas && \
    unzip /tmp/arthas.zip -d /opt/arthas && \
    rm /tmp/arthas.zip
