name: Docker Image CI

on:
  repository_dispatch:
  release:
    types: published
  watch:
    types: started

jobs:
  push_to_registry:
    name: build and push tdengine
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PWD }}

      - name: Build tdengine image
        uses: docker/build-push-action@v2
        with:
          context: tdengine/
          push: true
          build-args: |
            TD_ENGINE_VERSION=${{ secrets.TD_ENGINE_VERSION }}
          tags: |
            anjia0532/tdengine:${{ secrets.TD_ENGINE_VERSION }}
            anjia0532/tdengine:latest
          cache-from: type=registry,ref=anjia0532/tdengine:latest
          cache-to: type=inline

      - name: Build arthas-8-jdk-alpine
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=8-jdk-alpine
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-8-jdk-alpine:${{ secrets.ARTHAS_VERSION }}
            anjia0532/arthas-8-jdk-alpine:latest
          cache-from: type=registry,ref=anjia0532/arthas-8-jdk-alpine:latest
          cache-to: type=inline

      - name: Build arthas-8-Tunnel-jdk-alpine
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Tunnel-ServerDockerfile
          push: true
          build-args: |
            BASE_IMAGE=8-jdk-alpine
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-8-jdk-alpine:${{ secrets.ARTHAS_VERSION }}-tunnel-server
          cache-from: type=registry,ref=anjia0532/arthas-8-jdk-alpine:latest
          cache-to: type=inline

      - name: Build arthas-11-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=16-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-11-jdk-slim:${{ secrets.ARTHAS_VERSION }}
            anjia0532/arthas-11-jdk-slim:latest
          cache-from: type=registry,ref=anjia0532/arthas-11-jdk-slim:latest
          cache-to: type=inline

      - name: Build arthas-11-Tunnel-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Tunnel-ServerDockerfile
          push: true
          build-args: |
            BASE_IMAGE=16-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-11-jdk-slim:${{ secrets.ARTHAS_VERSION }}-tunnel-server
          cache-from: type=registry,ref=anjia0532/arthas-11-jdk-slim:latest
          cache-to: type=inline

          
      - name: Build arthas-16-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=16-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-16-jdk-slim:${{ secrets.ARTHAS_VERSION }}
            anjia0532/arthas-16-jdk-slim:latest
          cache-from: type=registry,ref=anjia0532/arthas-16-jdk-slim:latest
          cache-to: type=inline

      - name: Build arthas-16-Tunnel-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Tunnel-ServerDockerfile
          push: true
          build-args: |
            BASE_IMAGE=16-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-16-jdk-slim:${{ secrets.ARTHAS_VERSION }}-tunnel-server
          cache-from: type=registry,ref=anjia0532/arthas-16-jdk-slim:latest
          cache-to: type=inline

          
      - name: Build arthas-17-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=17-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-17-jdk-slim:${{ secrets.ARTHAS_VERSION }}
            anjia0532/arthas-17-jdk-slim:latest
          cache-from: type=registry,ref=anjia0532/arthas-17-jdk-slim:latest
          cache-to: type=inline

      - name: Build arthas-17-Tunnel-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Tunnel-ServerDockerfile
          push: true
          build-args: |
            BASE_IMAGE=17-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-17-jdk-slim:${{ secrets.ARTHAS_VERSION }}-tunnel-server
          cache-from: type=registry,ref=anjia0532/arthas-17-jdk-slim:latest
          cache-to: type=inline

      - name: Build arthas-18-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=18-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-18-jdk-slim:${{ secrets.ARTHAS_VERSION }}
            anjia0532/arthas-18-jdk-slim:latest
          cache-from: type=registry,ref=anjia0532/arthas-18-jdk-slim:latest
          cache-to: type=inline

      - name: Build arthas-18-Tunnel-jdk-slim
        uses: docker/build-push-action@v2
        with:
          context: arthas
          file: arthas/Tunnel-ServerDockerfile
          push: true
          build-args: |
            BASE_IMAGE=18-jdk-slim
            ARTHAS_VERSION=${{ secrets.ARTHAS_VERSION }}
          tags: |
            anjia0532/arthas-18-jdk-slim:${{ secrets.ARTHAS_VERSION }}-tunnel-server
          cache-from: type=registry,ref=anjia0532/arthas-18-jdk-slim:latest
          cache-to: type=inline